name: 'Reject PR review'
description: 'Reject PR review'
author: 'retzero'
inputs:
  filters:
    description: 'What to reject. Comma separated strings.'
    default: '!NOT-PERMITTED!'
  authors:
    description: 'By whom? Comma separated GitHub ID.'
    required: true
  auto-close-pr:
    description: 'Where or not to close PR.'
    default: false

runs:
  using: 'composite'
  steps:
    - name: Check review comment user
      continue-on-error: true
      id: user-check
      run: |
        while IFS=',' read -ra ADDR; do
          for i in "${ADDR[@]}"; do
            if [ "${i}" == "${{ github.event.comment.user.login }}" ]; then
              echo "desired-user=true" >> ${GITHUB_OUTPUT}
              break
            fi
          done
        done <<< "${{ inputs.authors }}"
      shell: bash

    - name: Check review comment
      if: steps.user-check.outputs.desired-user == 'true'
      run: |
        while IFS=',' read -ra ADDR; do
          for i in "${ADDR[@]}"; do
            pr_comment=$(echo "${{ github.event.comment.body }}" | tr '[:upper:]' '[:lower:]')
            filter=$(echo "${i}" | tr '[:upper:]' '[:lower:]')
            if [[ "${pr_comment}" == *"${filter}"* ]]; then
              if [ "${{ inputs.auto-close-pr }}" == "true" ]; then
                gh pr close ${{ github.event.pull_request.number }} -c "Auto-closing based on review comment."
              fi
              echo "Please check the comment posted by ${{ github.event.comment.user.login }}."
              exit 1
            fi
          done
        done <<< "${{ inputs.filters }}"
      shell: bash
