name: 'Reject PR review'
description: 'Reject PR review'
author: 'retzero'
runs:
  using: 'composite'
  steps:
    - name: Member assign
      run: |
        gh pr comment ${{ github.event.issue.number }} --body "Looks good!"
      shell: bash
