name: 'Reject PR review'
description: 'Reject PR review'
author: 'retzero'
runs:
  using: 'composite'
  steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "${{ github.event.pull_request.head.number }}"
        echo "${{ github.event.comment.body }}"
        echo "${{ github.event.comment }}"
      shell: bash
    - name: Member assign
      run: |
        set -x
        git branch
        git log -n1
        gh version
        gh pr comment ${{ github.pull_request.head.number }} --body "Looks good!"
      shell: bash
