name: 'Reject PR review'
description: 'Reject PR review'
author: 'retzero'
runs:
  using: 'composite'
  steps:
    - name: Member assign
      run: |
        set -x
        git branch
        git log -n1
        gh version
        gh pr comment ${{ github.event.issue.number }} --body "Looks good!"
      shell: bash
