name: 'Reject PR review'
description: 'Reject PR review'
author: 'retzero'
runs:
  using: 'composite'
  steps:
    - name: Member assign
      run: |
        gh issue edit "${{ github.event.issue.number }}" --add-assignee retzero
      shell: bash
